language: php

php:
    - 5.5
    - 5.4

install:
    - composer install --prefer-source

script:
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create
    - php app/console doctrine:fixtures:load --no-interaction
    - phpunit --colors -c app/ --coverage-clover clover.xml --coverage-text

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e489e71628740e8c2997
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false