anticom_showcase:
    resource: "@AnticomShowcaseBundle/Resources/config/routing.yml"
    prefix:   /

#region security
login:
    path: /login
    defaults: { _controller: AnticomShowcaseBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
#endregion