#region main routes
anticom_showcase_impress:
    path: /impress
    defaults: { _controller: AnticomShowcaseBundle:Default:impress }

anticom_showcase_contact:
    path: /contact
    defaults: { _controller: AnticomShowcaseBundle:Default:contact }

anticom_showcase_register:
    path: /register
    defaults: { _controller: AnticomShowcaseBundle:User:register}
#endregion

#region blog
anticom_showcase_blog_list:
    path: /blog/{page}
    defaults: {_controller: AnticomShowcaseBundle:Blog:list, page: 1}

anticom_showcase_blog_show:
    path: /blog/show/{id}
    defaults: {_controller: AnticomShowcaseBundle:Blog:show}

anticom_showcase_blog_new:
    path: /blog/new
    defaults: {_controller: AnticomShowcaseBundle:Blog:new}

anticom_showcase_blog_edit:
    path: /blog/edit/{id}
    defaults: {_controller: AnticomShowcaseBundle:Blog:edit}
#endregion

#region comments
anticom_showcase_comment_new:
    path: /blog/comment/new/{blogEntry}/{parentComment}
    defaults: {_controller: AnticomShowcaseBundle:Comment:new, parentComment: null}

anticom_showcase_comment_edit:
    path: /blog/comment/edit/{blogEntry}/{comment}
    defaults: {_controller: AnticomShowcaseBundle:Comment:edit, comment: null}
#endregion

#region user
#...
#endregion