parameters:
#    anticom_showcase.example.class: Anticom\ShowcaseBundle\Example

services:
#    anticom.access_denied_handler:
#            class: Anticom\ShowcaseBundle\EventListener\AnticomAccessDeniedListener
#            arguments:
#                session: @session
#            tags:
#                - { name: kernel.event_listener, event: security.kernel_response, method: handle }
    #anticom_showcase.example:
        #class: %anticom_showcase.example.class%
        #arguments: [@service_id, "plain_value", %parameter%]
