parameters:
    anticom_showcase.user_login.class: Anticom\ShowcaseBundle\Service\LoginEntryPoint
#    anticom_showcase.example.class: Anticom\ShowcaseBundle\Example

services:
    entry_point.user_login:
        class: %anticom_showcase.user_login.class%
        arguments: [ @router ] #I am going to use this for URL generation since I will be redirecting in my service
#    anticom_showcase.example:
#        class: %anticom_showcase.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
