Anticom\ShowcaseBundle\Entity\User:
#TODO: implement callback in Entity
#    constraints:
#        - Callback: [validate]
    properties:
        username:
            - NotNull:
                message: "Der Benutzername darf nicht leer sein"
            - NotBlank:
                message: "Der Benutzername darf nicht leer sein"
            - Length:
                min: 3
                minMessage: "Der Benutzername muss mindestens 3 Zeichen lang sein"
        email:
            - Email:
                message: "Bitte geben Sie eine gültige E-mailadresse ein"
            - Length:
                min: 6
                minMessage: "Die E-mailadresse muss mindestens 6 Zeichen lang sein"
        password:
            - NotBlank:
                message: "Bitte geben Sie ein passwort ein"

Anticom\ShowcaseBundle\Entity\BlogEntry:
    properties:
        title:
            - NotNull:
                message: "Der Blogeintrag muss einen Titel haben"
            - NotBlank:
                message: "Der Blogeintrag muss einen Titel haben"
            - Length:
                min: 5
                minMessage: "Der Titel muss mindestens 5 Zeichen lang sein"
        body:
            - NotNull:
                message: "Der Blogeintrag muss einen Text haben"
            - NotBlank:
                message: "Der Blogeintrag muss einen Text haben"
            - Length:
                min: 10
                minMessage: "Der Text muss mindestens 10 Zeichen lang sein"