<?php

namespace Anticom\ShowcaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogEntryRepository extends EntityRepository {
    public function findPrev(BlogEntry $blogEntry) {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT be FROM AnticomShowcaseBundle:BlogEntry be WHERE be.id < :currentId ORDER BY be.id DESC')
            ->setMaxResults(1)
            ->setParameter('currentId', $blogEntry->getId())
            ->getOneOrNullResult();
    }

    public function findNext(BlogEntry $blogEntry) {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT be FROM AnticomShowcaseBundle:BlogEntry be WHERE be.id > :currentId ORDER BY be.id ASC')
            ->setMaxResults(1)
            ->setParameter('currentId', $blogEntry->getId())
            ->getOneOrNullResult();
    }
}
